name: Build
on:
  push:
    branches: [ dev, main, hotfix/*, feature/*, release/* ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUNNER: github
      NODE_ENV: test
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
      - name: Install local dependencies
        run:  npm i
      - name: Create .env file
        run: |
          touch .env
          echo GG_RECAPTCHA_SCORE = "${{ vars.GG_RECAPTCHA_SCORE }}" >> .env
          echo GG_RECAPTCHA_SECRET = "${{ secrets.GG_RECAPTCHA_SECRET }}" >> .env
      - name: Execute tests suites
        run: npm run ci:test
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info